name: Deploy Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: Afrisinc/deployment-workflows/.github/workflows/deploy-ghcr.yml@main
    with:
      app-name: payment-dashboard
      environment: prod
      dockerfile-path: .
    secrets: inherit
