name: Deploy QA

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    uses: Afrisinc/deployment-workflows/.github/workflows/deploy-ghcr.yml@main
    with:
      app-name: payment-dashboard
      environment: qa
      dockerfile-path: .
